apiVersion: v1
kind: Service
metadata:
  name: mygateway
  namespace: default
  labels:
    app: mygateway
spec:
  selector:
    app: mygateway
  type: LoadBalancer
  ports:
  - name: http
    port: 8080
